version: '3'
services:
  dockerimagetest-api:
    image: stephengarnercontainers.azurecr.io/dockerimagetest-api:development
    container_name: dockerimagetest-api
    ports:
      - "80:80"
    restart: unless-stopped
    privileged: true
    depends_on:
      - ouroboros

  dockerimagetest-app:
    image: stephengarnercontainers.azurecr.io/dockerimagetest-app:development
    container_name: dockerimagetest-app
    restart: unless-stopped
    privileged: true
    depends_on:
      - dockerimagetest-api
      - ouroboros
    links:
      - dockerimagetest-api

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      LOG_LEVEL: info
      CLEANUP: "true"
      LATEST: "true"
      INTERVAL: 300
      MONITOR: "dockerimagetest-api dockerimagetest-app"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/root/.docker/config.json